import numpy as np

DBNAME = "dsbl2"

BOATS = 6
FLIGHTS = 16

TEAMS = [
    "SVWu", "ETUF", "YCM", "SCSz", "WSW", "KaR",
    "BuSC", "LYC", "ASV-HH", "CYCM", "WYD", "SCV",
    "PYC", "BOH-YC", "LSV", "HSC", "ENSFR", "BSC"
]

BUCHSTABEN = {'OCS': BOATS + 1,
              'DSQ': BOATS + 1,
              'DNF': BOATS + 1,
              'DNC': BOATS + 1,
              'OSC' : BOATS + 1,
              'RET': BOATS + 1,
              'NSC': BOATS + 1,
              'No result': np.nan, }

PAIRINGLIST = [
    """Flight Race Boat 1 Boat 2 Boat 3 Boat 4 Boat 5 Boat 6
1 SVWu ETUF YCM SCSz WSW KaR
2 BuSC LYC ASV-HH CYCM WYD SCV
3 PYC BOH-YC LSV HSC ENSFR BSC
4 PYC YCM LSV SCV KaR CYCM
5 BOH-YC ENSFR WSW LYC ASV-HH SCSz
6 BSC SVWu HSC WYD ETUF BuSC
7 YCM SVWu LYC ENSFR LSV BuSC
8 KaR WSW CYCM BOH-YC BSC WYD
9 HSC SCV SCSz ASV-HH PYC ETUF
10 CYCM BSC SCSz SVWu PYC LYC
11 ETUF ASV-HH BOH-YC KaR BuSC LSV
12 WYD HSC ENSFR WSW SCV YCM
13 CYCM HSC BuSC BOH-YC SCSz YCM
14 LYC LSV ETUF BSC SCV WSW
15 ENSFR PYC KaR WYD SVWu ASV-HH
16 WSW PYC BSC BuSC YCM ASV-HH
17 SCV CYCM SVWu ETUF BOH-YC ENSFR
18 LSV SCSz WYD KaR LYC HSC
19 YCM BOH-YC WYD ETUF LYC PYC
20 SCSz KaR SCV ENSFR BuSC BSC
21 ASV-HH CYCM WSW LSV HSC SVWu
22 ASV-HH YCM BOH-YC SCV BSC SVWu
23 LYC ENSFR KaR HSC CYCM ETUF
24 WSW BuSC PYC SCSz WYD LSV
25 HSC BSC ASV-HH YCM KaR LYC
26 WYD ETUF ENSFR LSV CYCM SCSz
27 SCV WSW PYC BuSC SVWu BOH-YC
28 SCSz WYD YCM BSC LSV BOH-YC
29 KaR SCV SVWu PYC HSC LYC
30 ENSFR ASV-HH BuSC WSW ETUF CYCM
31 ENSFR SCSz LYC WSW BOH-YC SCV
32 LSV BuSC CYCM PYC YCM KaR
33 ETUF WYD BSC SVWu ASV-HH HSC
34 ETUF CYCM BSC YCM ENSFR PYC
35 BuSC KaR HSC LYC BOH-YC WSW
36 SVWu LSV SCV ASV-HH SCSz WYD
37 HSC LSV SCV ETUF WSW YCM
38 BSC SCSz KaR SVWu BuSC ENSFR
39 BOH-YC LYC ASV-HH CYCM PYC WYD
40 WSW LYC SVWu CYCM BSC LSV
41 SCV BuSC ENSFR WYD HSC PYC
42 YCM BOH-YC ETUF ASV-HH SCSz KaR
43 WYD SCV CYCM BSC WSW KaR
44 ASV-HH ENSFR PYC BOH-YC LSV HSC
45 LYC SVWu YCM BuSC ETUF SCSz
46 BOH-YC SVWu YCM KaR WYD ENSFR
47 PYC ETUF HSC SCSz CYCM WSW
48 LSV BSC BuSC SCV LYC ASV-HH
""",
    """Flight Race Boat 1 Boat 2 Boat 3 Boat 4 Boat 5 Boat 6
1 WSW SCV LYC SVWu WYD BOH-YC
2 ASV-HH BSC PYC ETUF BuSC KaR
3 YCM ENSFR SCSz LSV HSC CYCM
4 YCM LYC SCSz KaR BOH-YC ETUF
5 ENSFR HSC WYD BSC PYC SVWu
6 CYCM WSW LSV BuSC SCV ASV-HH
7 LYC WSW BSC HSC SCSz ASV-HH
8 BOH-YC WYD ETUF ENSFR CYCM BuSC
9 LSV KaR SVWu PYC YCM SCV
10 ETUF CYCM SVWu WSW YCM BSC
11 SCV PYC ENSFR BOH-YC ASV-HH SCSz
12 BuSC LSV HSC WYD KaR LYC
13 ETUF LSV ASV-HH ENSFR SVWu LYC
14 BSC SCSz SCV CYCM KaR WYD
15 HSC YCM BOH-YC BuSC WSW PYC
16 WYD YCM CYCM ASV-HH LYC PYC
17 KaR ETUF WSW SCV ENSFR HSC
18 SCSz SVWu BuSC BOH-YC BSC LSV
19 LYC ENSFR BuSC SCV BSC YCM
20 SVWu BOH-YC KaR HSC ASV-HH CYCM
21 PYC ETUF WYD SCSz LSV WSW
22 PYC LYC ENSFR KaR CYCM WSW
23 BSC HSC BOH-YC LSV ETUF SCV
24 WYD ASV-HH YCM SVWu BuSC SCSz
25 LSV CYCM PYC LYC BOH-YC BSC
26 BuSC SCV HSC SCSz ETUF SVWu
27 KaR WYD YCM ASV-HH WSW ENSFR
28 SVWu BuSC LYC CYCM SCSz ENSFR
29 BOH-YC KaR WSW YCM LSV BSC
30 HSC PYC ASV-HH WYD SCV ETUF
31 HSC SVWu BSC WYD ENSFR KaR
32 SCSz ASV-HH ETUF YCM LYC BOH-YC
33 SCV BuSC CYCM WSW PYC LSV
34 SCV ETUF CYCM LYC HSC YCM
35 ASV-HH BOH-YC LSV BSC ENSFR WYD
36 WSW SCSz KaR PYC SVWu BuSC
37 LSV SCSz KaR SCV WYD LYC
38 CYCM SVWu BOH-YC WSW ASV-HH HSC
39 ENSFR BSC PYC ETUF YCM BuSC
40 WYD BSC WSW ETUF CYCM SCSz
41 KaR ASV-HH HSC BuSC LSV YCM
42 LYC ENSFR SCV PYC SVWu BOH-YC
43 BuSC KaR ETUF CYCM WYD BOH-YC
44 PYC HSC YCM ENSFR SCSz LSV
45 BSC WSW LYC ASV-HH SCV SVWu
46 ENSFR WSW LYC BOH-YC BuSC HSC
47 YCM SCV LSV SVWu ETUF WYD
48 SCSz CYCM ASV-HH KaR BSC PYC
""",
    """Flight Race Boat 1 Boat 2 Boat 3 Boat 4 Boat 5 Boat 6
1 WYD KaR BSC WSW BuSC ENSFR
2 PYC CYCM YCM SCV ASV-HH BOH-YC
3 LYC HSC SVWu SCSz LSV ETUF
4 LYC BSC SVWu BOH-YC ENSFR SCV
5 HSC LSV BuSC CYCM YCM WSW
6 ETUF WYD SCSz ASV-HH KaR PYC
7 BSC WYD CYCM LSV SVWu PYC
8 ENSFR BuSC SCV HSC ETUF ASV-HH
9 SCSz BOH-YC WSW YCM LYC KaR
10 SCV ETUF WSW WYD LYC CYCM
11 KaR YCM HSC ENSFR PYC SVWu
12 ASV-HH SCSz LSV BuSC BOH-YC BSC
13 SCV SCSz PYC HSC WSW BSC
14 CYCM SVWu KaR ETUF BOH-YC BuSC
15 LSV LYC ENSFR ASV-HH WYD YCM
16 BuSC LYC ETUF PYC BSC YCM
17 BOH-YC SCV WYD KaR HSC LSV
18 SVWu WSW ASV-HH ENSFR CYCM SCSz
19 BSC HSC ASV-HH KaR CYCM LYC
20 WSW ENSFR BOH-YC LSV PYC ETUF
21 YCM SCV BuSC SVWu SCSz WYD
22 YCM BSC HSC BOH-YC ETUF WYD
23 CYCM LSV ENSFR SCSz SCV KaR
24 BuSC PYC LYC WSW ASV-HH SVWu
25 SCSz ETUF YCM BSC ENSFR CYCM
26 ASV-HH KaR LSV SVWu SCV WSW
27 BOH-YC BuSC LYC PYC WYD HSC
28 WSW ASV-HH BSC ETUF SVWu HSC
29 ENSFR BOH-YC WYD LYC SCSz CYCM
30 LSV YCM PYC BuSC KaR SCV
31 LSV WSW CYCM BuSC HSC BOH-YC
32 SVWu PYC SCV LYC BSC ENSFR
33 KaR ASV-HH ETUF WYD YCM SCSz
34 KaR SCV ETUF BSC LSV LYC
35 PYC ENSFR SCSz CYCM HSC BuSC
36 WYD SVWu BOH-YC YCM WSW ASV-HH
37 SCSz SVWu BOH-YC KaR BuSC BSC
38 ETUF WSW ENSFR WYD PYC LSV
39 HSC CYCM YCM SCV LYC ASV-HH
40 BuSC CYCM WYD SCV ETUF SVWu
41 BOH-YC PYC LSV ASV-HH SCSz LYC
42 BSC HSC KaR YCM WSW ENSFR
43 ASV-HH BOH-YC SCV ETUF BuSC ENSFR
44 YCM LSV LYC HSC SVWu SCSz
45 CYCM WYD BSC PYC KaR WSW
46 HSC WYD BSC ENSFR ASV-HH LSV
47 LYC KaR SCSz WSW SCV BuSC
48 SVWu ETUF PYC BOH-YC CYCM YCM
""",
"""Flight Race Boat 1 Boat 2 Boat 3 Boat 4 Boat 5 Boat 6
1 BuSC BOH-YC CYCM WYD ASV-HH HSC
2 YCM ETUF LYC KaR PYC ENSFR
3 BSC LSV WSW SVWu SCSz SCV
4 BSC CYCM WSW ENSFR HSC KaR
5 LSV SCSz ASV-HH ETUF LYC WYD
6 SCV BuSC SVWu PYC BOH-YC YCM
7 CYCM BuSC ETUF SCSz WSW YCM
8 HSC ASV-HH KaR LSV SCV PYC
9 SVWu ENSFR WYD LYC BSC BOH-YC
10 KaR SCV WYD BuSC BSC ETUF
11 BOH-YC LYC LSV HSC YCM WSW
12 PYC SVWu SCSz ASV-HH ENSFR CYCM
13 KaR SVWu YCM LSV WYD CYCM
14 ETUF WSW BOH-YC SCV ENSFR ASV-HH
15 SCSz BSC HSC PYC BuSC LYC
16 ASV-HH BSC SCV YCM CYCM LYC
17 ENSFR KaR BuSC BOH-YC LSV SCSz
18 WSW WYD PYC HSC ETUF SVWu
19 CYCM LSV PYC BOH-YC ETUF BSC
20 WYD HSC ENSFR SCSz YCM SCV
21 LYC KaR ASV-HH WSW SVWu BuSC
22 LYC CYCM LSV ENSFR SCV BuSC
23 ETUF SCSz HSC SVWu KaR BOH-YC
24 ASV-HH YCM BSC WYD PYC WSW
25 SVWu SCV LYC CYCM HSC ETUF
26 PYC BOH-YC SCSz WSW KaR WYD
27 ENSFR ASV-HH BSC YCM BuSC LSV
28 WYD PYC CYCM SCV WSW LSV
29 HSC ENSFR BuSC BSC SVWu ETUF
30 SCSz LYC YCM ASV-HH BOH-YC KaR
31 SCSz WYD ETUF ASV-HH LSV ENSFR
32 WSW YCM KaR BSC CYCM HSC
33 BOH-YC PYC SCV BuSC LYC SVWu
34 BOH-YC KaR SCV CYCM SCSz BSC
35 YCM HSC SVWu ETUF LSV ASV-HH
36 BuSC WSW ENSFR LYC WYD PYC
37 SVWu WSW ENSFR BOH-YC ASV-HH CYCM
38 SCV WYD HSC BuSC YCM SCSz
39 LSV ETUF LYC KaR BSC PYC
40 ASV-HH ETUF BuSC KaR SCV WSW
41 ENSFR YCM SCSz PYC SVWu BSC
42 CYCM LSV BOH-YC LYC WYD HSC
43 PYC ENSFR KaR SCV ASV-HH HSC
44 LYC SCSz BSC LSV WSW SVWu
45 ETUF BuSC CYCM YCM BOH-YC WYD
46 LSV BuSC CYCM HSC PYC SCSz
47 BSC BOH-YC SVWu WYD KaR ASV-HH
48 WSW SCV YCM ENSFR ETUF LYC
""",
"""Flight Race Boat 1 Boat 2 Boat 3 Boat 4 Boat 5 Boat 6
1 ASV-HH ENSFR ETUF BuSC PYC LSV
2 LYC SCV BSC BOH-YC YCM HSC
3 CYCM SCSz WYD WSW SVWu KaR
4 CYCM ETUF WYD HSC LSV BOH-YC
5 SCSz SVWu PYC SCV BSC BuSC
6 KaR ASV-HH WSW YCM ENSFR LYC
7 ETUF ASV-HH SCV SVWu WYD LYC
8 LSV PYC BOH-YC SCSz KaR YCM
9 WSW HSC BuSC BSC CYCM ENSFR
10 BOH-YC KaR BuSC ASV-HH CYCM SCV
11 ENSFR BSC SCSz LSV LYC WYD
12 YCM WSW SVWu PYC HSC ETUF
13 BOH-YC WSW LYC SCSz BuSC ETUF
14 SCV WYD ENSFR KaR HSC PYC
15 SVWu CYCM LSV YCM ASV-HH BSC
16 PYC CYCM KaR LYC ETUF BSC
17 HSC BOH-YC ASV-HH ENSFR SCSz SVWu
18 WYD BuSC YCM LSV SCV WSW
19 ETUF SCSz YCM ENSFR SCV CYCM
20 BuSC LSV HSC SVWu LYC KaR
21 BSC BOH-YC PYC WYD WSW ASV-HH
22 BSC ETUF SCSz HSC KaR ASV-HH
23 SCV SVWu LSV WSW BOH-YC ENSFR
24 PYC LYC CYCM BuSC YCM WYD
25 WSW KaR BSC ETUF LSV SCV
26 YCM ENSFR SVWu WYD BOH-YC BuSC
27 HSC PYC CYCM LYC ASV-HH SCSz
28 BuSC YCM ETUF KaR WYD SCSz
29 LSV HSC ASV-HH CYCM WSW SCV
30 SVWu BSC LYC PYC ENSFR BOH-YC
31 SVWu BuSC SCV PYC SCSz HSC
32 WYD LYC BOH-YC CYCM ETUF LSV
33 ENSFR YCM KaR ASV-HH BSC WSW
34 ENSFR BOH-YC KaR ETUF SVWu CYCM
35 LYC LSV WSW SCV SCSz PYC
36 ASV-HH WYD HSC BSC BuSC YCM
37 WSW WYD HSC ENSFR PYC ETUF
38 KaR BuSC LSV ASV-HH LYC SVWu
39 SCSz SCV BSC BOH-YC CYCM YCM
40 PYC SCV ASV-HH BOH-YC KaR WYD
41 HSC LYC SVWu YCM WSW CYCM
42 ETUF SCSz ENSFR BSC BuSC LSV
43 YCM HSC BOH-YC KaR PYC LSV
44 BSC SVWu CYCM SCSz WYD WSW
45 SCV ASV-HH ETUF LYC ENSFR BuSC
46 SCSz ASV-HH ETUF LSV YCM SVWu
47 CYCM ENSFR WSW BuSC BOH-YC PYC
48 WYD KaR LYC HSC SCV BSC
"""
]